// Real integration tests against the actual ConversationDO state
// machine — not mocks, not a re-implementation of the logic. Made
// possible by STUB_MODE (see Env.STUB_MODE's doc, types.ts): every
// HOFJ/Stripe/AI call is instant and deterministic, driven here through
// the test DSL in engine/ai.ts's stubInterpret() and the failure
// scenarios in hofj/client.ts's stubRequest() (STUB_SCENARIOS) — the
// same underlying mechanism loadtest/scale-50k.js already used, now
// also making the conversation.ts state machine itself testable
// (Giuseppe, 2026-09-15: "possiamo usare lo STUB_MODE che abbiamo usato
// per il load test per scrivere i test almeno sulla macchina a stati").
//
// Scope, deliberately: this covers state TRANSITIONS (which stage
// follows which, what data survives a compromise/error, what a
// deterministic scenario ends in) — not reply wording (the stub always
// returns "[stub:<kind>]", see say()) and not real NLU accuracy (that's
// scripts/prompt-suite.mjs against real models). Not covered here either:
// quota-gate backpressure under real concurrency (see
// loadtest/scale-50k.js for that), and multi-conversation isolation
// (implied by one Durable Object per conversation, not re-tested).
import { env as rawEnv } from "cloudflare:test";
import { describe, expect, it } from "vitest";
import type { Env, UserProfile } from "../src/types";

// worker-configuration.d.ts (generated by `wrangler types`) leaves DO
// bindings as the untyped generic DurableObjectNamespace, not
// DurableObjectNamespace<ConversationDO> — cast to this project's own,
// correctly-typed Env (src/types.ts) instead of fighting codegen for it.
const env = rawEnv as unknown as Env;

let counter = 0;
/** A fresh, uniquely-named ConversationDO instance per test — DO state
 * persists by name, so reusing a name would leak state between tests. */
function freshConversation() {
  counter += 1;
  return env.CONVERSATION.getByName(`conversation-test-${counter}-${Date.now()}`);
}

const TRAVELLER_DSL = "firstName:Mario|lastName:Rossi|email:mario@example.com|phone:1234567890|homeCity:Milano";

function tripDsl(extra = ""): string {
  return `sport:tennis|destCity:Roma|dateFrom:25 settembre 2026|budget:400|adults:1${extra}`;
}

describe("ConversationDO state machine (STUB_MODE integration tests)", () => {
  it("starts by collecting traveller data, not trip details, when nothing is known yet", async () => {
    const stub = freshConversation();
    // "noop:1" is valid test-DSL syntax with no recognized keys — every
    // slot/traveller field stays unset, isolating "what does a truly
    // blank conversation ask first" from any of the DSL's own defaults.
    const r = await stub.handleMessage("noop:1");
    expect(r.state.stage).toBe("collecting_traveller");
    expect(r.state.slots.sport).toBeNull();
  });

  it("happy path: trip + traveller data together reaches an exact proposal, then booked", async () => {
    const stub = freshConversation();
    const r1 = await stub.handleMessage(`${tripDsl()}|${TRAVELLER_DSL}`);
    expect(r1.state.stage).toBe("proposing");
    expect(r1.state.proposal?.category).toBe("exact");
    expect(r1.state.proposal?.candidate.productId).toBe("1");

    const r2 = await stub.handleMessage("decision:yes");
    expect(r2.state.stage).toBe("booked");
    expect(r2.state.reservationCode).toBeTruthy();
    expect(r2.state.itineraryId).toBeTruthy();
  });

  it("skips traveller fields already known from a saved profile, asking only for what's missing", async () => {
    const stub = freshConversation();
    const profile: UserProfile = {
      firstName: "Giulia",
      email: "giulia@example.com",
      city: "Torino",
      preferredSport: null,
      householdSize: null,
      economicTier: null,
    };
    const r = await stub.handleMessage("noop:1", profile);
    expect(r.state.stage).toBe("collecting_traveller");
    expect(r.state.traveller.firstName).toBe("Giulia");
    expect(r.state.traveller.email).toBe("giulia@example.com");
    expect(r.state.traveller.city).toBe("Torino");
    // lastName/phone aren't part of a UserProfile — still genuinely missing.
    expect(r.state.traveller.lastName).toBeNull();
  });

  it("rejecting the only available proposal searches again honestly instead of looping", async () => {
    const stub = freshConversation();
    await stub.handleMessage(`${tripDsl()}|${TRAVELLER_DSL}`);
    const r = await stub.handleMessage("decision:no");
    // Only one stub product exists by default; rejecting it leaves
    // nothing else to propose.
    expect(r.state.stage).toBe("collecting");
    expect(r.state.proposal).toBeNull();
    expect(r.state.rejectedProductIds).toContain("1");
  });

  it("date_shift scenario: renegotiates the date on the SAME package (never presented as a different one) before booking", async () => {
    const stub = freshConversation();
    await stub.handleMessage(`${tripDsl("|preferences:SCENARIO:date_shift")}|${TRAVELLER_DSL}`);
    const r1 = await stub.handleMessage("decision:yes");
    expect(r1.state.stage).toBe("proposing");
    expect(r1.state.proposal?.compromise?.kind).toBe("date");
    expect(r1.state.proposal?.candidate.productId).toBe("9001");
    expect(r1.state.slots.dateFrom).toBe("2026-01-01"); // committed to the offered date

    const r2 = await stub.handleMessage("decision:yes");
    expect(r2.state.stage).toBe("booked");
    expect(r2.state.proposal?.candidate.productId).toBe("9001"); // still the same package
  });

  it("price_changed scenario: the real cart price differs from what search advertised, surfaced as a compromise before booking", async () => {
    const stub = freshConversation();
    await stub.handleMessage(`${tripDsl("|preferences:SCENARIO:price_changed")}|${TRAVELLER_DSL}`);
    const r1 = await stub.handleMessage("decision:yes");
    expect(r1.state.stage).toBe("proposing");
    expect(r1.state.proposal?.compromise?.kind).toBe("price");
    // The real cart genuinely was opened (createItinerary succeeded) —
    // only the PRICE was re-verified and found different, so a real
    // itineraryId already exists at this point, correctly.
    expect(r1.state.itineraryId).toBeTruthy();

    const r2 = await stub.handleMessage("decision:yes");
    expect(r2.state.stage).toBe("booked");
  });

  it("broken_product_config scenario (real case, Giuseppe 2026-09-15, productId 19 \"M3 Padel Week\"): a cart that genuinely opens but whose immediate re-read permanently 502s rejects the product with the real reason and clears the abandoned cart, instead of being misread as a transient 'system is slow' error", async () => {
    const stub = freshConversation();
    await stub.handleMessage(`${tripDsl("|preferences:SCENARIO:broken_product_config")}|${TRAVELLER_DSL}`);
    const r1 = await stub.handleMessage("decision:yes");
    expect(r1.state.stage).toBe("proposing");
    expect(r1.state.proposal?.candidate.productId).not.toBe("9006");
    expect(r1.state.rejectedProductIds).toContain("9006");
    // The abandoned cart from the broken product must not linger.
    expect(r1.state.itineraryId).toBeNull();

    const r2 = await stub.handleMessage("decision:yes");
    expect(r2.state.stage).toBe("booked");
  });

  it("unavailable scenario (requested date == the scenario's own minDate, isolating this branch from the date-fallback one): rejects the original package for a REAL reason and finds a genuine alternative", async () => {
    const stub = freshConversation();
    // 1 gennaio 2026 matches STUB_SCENARIOS.unavailable's own minDate —
    // createItinerary's requestedDate === candidate.minDate from the
    // first attempt, so conversation.ts can't (and shouldn't) read this
    // as "maybe just a date problem" and tries the fallback first (see
    // ARCHITECTURE.md's "unavailable" scenario doc, hofj/client.ts, for
    // why a mismatched date would hit date_shift_confirm before this
    // branch instead).
    await stub.handleMessage(`sport:tennis|destCity:Roma|dateFrom:1 gennaio 2026|budget:400|adults:1|preferences:SCENARIO:unavailable|${TRAVELLER_DSL}`);
    const r1 = await stub.handleMessage("decision:yes");
    expect(r1.state.stage).toBe("proposing");
    expect(r1.state.proposal?.candidate.productId).not.toBe("9003");
    expect(r1.state.rejectedProductIds).toContain("9003");

    const r2 = await stub.handleMessage("decision:yes");
    expect(r2.state.stage).toBe("booked");
  });

  it("customer_rejected scenario: a 400 on putCustomer resets traveller data and asks again, then succeeds on retry without losing the trip", async () => {
    const stub = freshConversation();
    await stub.handleMessage(`${tripDsl("|preferences:SCENARIO:customer_rejected")}|${TRAVELLER_DSL}`);
    const r1 = await stub.handleMessage("decision:yes");
    expect(r1.state.stage).toBe("collecting_traveller");
    expect(r1.state.traveller.firstName).toBeNull(); // reset
    expect(r1.state.proposal).not.toBeNull(); // the trip itself survives

    const r2 = await stub.handleMessage(TRAVELLER_DSL);
    expect(r2.state.stage).toBe("booked");
  });

  it("never_confirms scenario: a real successful payment with a booking that never confirms fails honestly, never claims 'booked', and logs a follow-up", async () => {
    const stub = freshConversation();
    await stub.handleMessage(`${tripDsl("|preferences:SCENARIO:never_confirms")}|${TRAVELLER_DSL}`);
    const r = await stub.handleMessage("decision:yes");
    expect(r.state.stage).toBe("failed");
    expect(r.state.paymentStatus).toBe("succeeded");
    expect(r.state.reservationCode).toBeNull();
    expect(r.state.followUpLogged).toBe(true);
    expect(r.state.failureReason).toContain("BookingInitiated");
  });

  it("a conversation already in the terminal 'booked' stage doesn't restart the flow on a new message", async () => {
    const stub = freshConversation();
    await stub.handleMessage(`${tripDsl()}|${TRAVELLER_DSL}`);
    await stub.handleMessage("decision:yes");
    const r = await stub.handleMessage("qualsiasi altra cosa");
    expect(r.state.stage).toBe("booked");
  });
});
